### ISSUE TITLE
Name typo for arrow-down-to-braket

### ISSUE THREAD

**Issue by nickolasgregory** [themesberg/flowbite-icons#11]
`arrow-down-to-braket.svg` should be
`arrow-down-to-bracket.svg`

**Comment by sparecycles** [comment]
@nickolasgregory 

I missed that one!  There's a whole bunch of other typos and inconsistencies that I tried to capture here:

https://github.com/themesberg/flowbite-svelte-icons/pull/13

**Comment by sparecycles** [comment]
https://github.com/themesberg/flowbite-icons/pull/14 implements this and more
