### ISSUE TITLE
Address book wrong file name, open-book missing on outline directory

### ISSUE THREAD

**Issue by kingroho** [themesberg/flowbite-icons#15]
Hello, nice set of icons.

Just want to file some issues I have seen. As the title says, address-book says adress-book and open-book is missing on outline directory.

# Issues Lists

### Incorrect Spelling
- `adress-book`

### Missing on *outline* directory.
- `open-book`

### Missing on *solid directory.
- `file-pen`
- `cog`

---

Will update this thread if I see new issues.

Thanks and have a great day.

**Comment by sparecycles** [comment]
outline has `book-open`

Fixed this, and the spelling issue in
https://github.com/themesberg/flowbite-icons/pull/14 

also, `cog` is renamed to `gear`, and `file-pen` to `file-edit` (consistency with both solid and outline)
