### ISSUE TITLE
Icon settings

### ISSUE THREAD

**Issue by gi4no** [themesberg/flowbite-icons#16]
Please add the icon for the settings

<img width="54" alt="Screenshot 2023-09-15 at 13 10 34" src="https://github.com/themesberg/flowbite-icons/assets/11884245/a9853b78-a28f-44ba-bf69-5198f1f1ef4d">

**Comment by sparecycles** [comment]
this is currently `cog` in the outline folder

[src/outline/general/cog.svg](https://github.com/themesberg/flowbite-icons/blob/2bb7368bd7e031dcd9eca88086f3627085d18cd3/src/outline/general/cog.svg)
