### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by tbredillet** [themesberg/flowbite-icons#42]
Hello,

Is it possible to add more social media icons ?

Instagram and what'sapp is missing I think

Thank you

**Comment by SutuSebastian** [comment]
> Hello,
> 
> 
> 
> Is it possible to add more social media icons ?
> 
> 
> 
> Instagram and what'sapp is missing I think
> 
> 
> 
> Thank you

Check the last release here:

https://github.com/themesberg/flowbite-icons/releases/tag/v1.2.0
