### ISSUE TITLE
Add a save icon

### ISSUE THREAD

**Issue by vincentrolfs** [themesberg/flowbite-icons#5]
Thank you for this resource, it's extremely helpful.

Any possibility to add a save icon? I feel like that's a very common icon that's missing here. Something like this: https://mui.com/material-ui/material-icons/?query=save&selected=Save

**Comment by zoltanszogyenyi** [comment]
Hello @vincentrolfs,

Thank you for the kind words!

@robert1508 - let's add a `save` icon to our upcoming batch of icons.

Cheers,
Zoltan

**Comment by ap1969** [comment]
Please do this!

**Comment by SutuSebastian** [comment]
Added in [v1.2.0](https://github.com/themesberg/flowbite-icons/releases/tag/v1.2.0) release under `floppy-disk.svg` and `floppy-disk-alt.svg` names.
