### ISSUE TITLE
Video icon name solid and outline is inconsistent 

### ISSUE THREAD

**Issue by JackNeto** [themesberg/flowbite-icons#9]
One is called `video` and the other one is called `video-camera`

https://github.com/themesberg/flowbite-icons/blob/main/src/solid/media/video.svg
https://github.com/themesberg/flowbite-icons/blob/main/src/outline/media/video-camera.svg

Related to: https://github.com/themesberg/flowbite-svelte-icons/issues/8

**Comment by sparecycles** [comment]
https://github.com/themesberg/flowbite-icons/pull/14 fixes this and more
